# Site settings
title: hoonti06
url: "https://hoonti06.gitlab.io"
baseurl: ""
description: >
    hoonti06 블로그

# My information
email: hoonti06@gmail.com
author: hoonti06
profile: junior programmer
gitlab_username: hoonti06
# disqus_shortname: none

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-pandoc
  - jekyll-pandoc-rouge
  - jekyll-mermaid
  - jekyll-pandoc-mermaid
 #- jekyll-pandoc-multiple-format
 #- jekyll-youtube

permalink: /blog/:year/:month/:day/:title/

# kramdown settings
#markdown: kramdown
#highlighter: rouge
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true
#   #span:
#     #line_numbers: true


# jekyll-pandoc settings
markdown: Pandoc
pandoc:
  extensions:
    - toc
    - toc-depth=6
    - standalone
    - highlight-style=pygments
    #- no-highlight

highlighter: rouge

# jekyll-pandoc-rouge settings
pandoc_rouge:
  use: true
  lineno:
    use: true
    #include:
    # - c
    # - c++
    #exclude:
    # - c
    # - c++

# jekyll-mermaid settinges
mermaid:
  src: 'https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js'


# jekyll-pandoc-multiple-formats settings
#markdown: pandoc
#pandoc:
#    skip:
#      full: false
#      posts: false
#      categories: false
#    bundle_permalink: ':output_ext/:slug.:output_ext'
#    papersize: 'a5paper'
#    sheetsize: 'a4paper'
#    imposition: true
#    binder: true
#    covers_dir: assets/covers
#    signature: 20
#    full_file: true
#
#    flags: '--smart'
#    site_flags: '--toc --toc-depth=6 --standalone --highlight-type=pygments'
#    outputs:
#      latex:
#      pdf: '--latex-engine=xelatex'
#      epub: '--epub-chapter-level=2'
#    lang:
#      ar:
#        all: '-V mainfont="Amiri"'
#        pdf: '--include-in-header=_layouts/rtl.tex'

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: hoonti06
  shortname: hoonti06

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

original: "https://gitlab.com/hoonti06/hoonti06.gitlab.io/blob/master/_wiki"
blame: "https://gitlab.com/hoonti06/hoonti06.gitlab.io/blame/master/_wiki"

timezone: "Asia/Seoul"

# Search setting

