# Site settings
title: hoonti06
url: "https://hoonti06.github.io"
baseurl: ""
description: >
    hoonti06 블로그

# My information
email: hoonti06@gmail.com
author: hoonti06
profile: junior programmer
github_username: hoonti06
# disqus_shortname: none

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: hoonti06
  shortname: hoonti06

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/hoonti06/hoonti06.github.io/blame/master/_wiki"
edit: "https://github.com/hoonti06/hoonti06.github.io/edit/master/_wiki"
issue: "https://github.com/hoonti06/hoonti06.github.io/issues/new"

timezone: "Asia/Seoul"

theme: jekyll-theme-midnight
