# Site settings
title: hoonti06
url: "https://hoonti06.gitlab.io"
baseurl: ""
description: >
    hoonti06 블로그

# My information
email: hoonti06@gmail.com
author: hoonti06
profile: junior programmer
gitlab_username: hoonti06
# disqus_shortname: none

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-pandoc

permalink: /blog/:year/:month/:day/:title/

# kramdown settings
#markdown: kramdown
#highlighter: rouge
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true
#   #span:
#     #line_numbers: true


# pandoc settings
markdown: Pandoc
highlighter: rouge
pandoc:
  extensions:
    - toc
    - toc-depth=6
    - standalone
    - highlight-style=pygments
    #- no-highlight


paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: hoonti06
  shortname: hoonti06

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

original: "https://gitlab.com/hoonti06/hoonti06.gitlab.io/blob/master/_wiki"
blame: "https://gitlab.com/hoonti06/hoonti06.gitlab.io/blame/master/_wiki"

timezone: "Asia/Seoul"

# Search setting

